[package]
name = "awesome-rust-tools"
version = "1.0.0"
authors = ["Pawel Kraszewski <pawel@kraszewscy.net>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_yaml = "^0"
serde_derive = "^1"
clap = "^2"

